### ISSUE TITLE
Log in page not taking full height

### ISSUE THREAD

**Issue by anoj-kt** [anoj-kt/finalproject-frontend#9]
**Issue on**
Component: UserLogin
Path: /auth/login

**Description**
All components together do not take full height on desktop version.

**Comment by onureredo** [comment]
suggestion: viewport "?"

**Comment by anoj-kt** [comment]
Fixed!

Solution: Used a media query based on height to set height of login component to **'calc(100vh - (162.44px + 182.01px))'**
